use_frameworks!

platform :ios, '9.0'

target 'QMangoFix_Example' do
  pod 'QMangoFix', :path => '../'  


  target 'QMangoFix_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
